# Generated by Django 2.1.5 on 2019-10-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner_Platter',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.MenuItem')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=5)),
            ],
            bases=('orders.menuitem',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.MenuItem')),
            ],
            bases=('orders.menuitem',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.MenuItem')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=5)),
                ('special', models.BooleanField()),
                ('sicilian', models.BooleanField()),
                ('top_number', models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three')])),
            ],
            bases=('orders.menuitem',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.MenuItem')),
            ],
            bases=('orders.menuitem',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.MenuItem')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=5)),
            ],
            bases=('orders.menuitem',),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='orders.MenuItem'),
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('pizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Pizza')),
                ('topps', models.ManyToManyField(to='orders.Topping')),
            ],
            bases=('orders.pizza',),
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('sub_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Sub')),
                ('extras', models.ManyToManyField(to='orders.Extra')),
            ],
            bases=('orders.sub',),
        ),
    ]
