# Generated by Django 2.1.5 on 2019-10-29 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_pizza_top_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('pizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Pizza')),
            ],
            bases=('orders.pizza',),
        ),
        migrations.RemoveField(
            model_name='dinner_platter',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='sicilian',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='special',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.AddField(
            model_name='dinner_platter',
            name='large_price',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='dinner_platter',
            name='small_price',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='pizza',
            name='large_price',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='pizza',
            name='small_price',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='sub',
            name='large_price',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='sub',
            name='small_price',
            field=models.FloatField(default=10),
        ),
    ]
