# Generated by Django 2.1.5 on 2019-10-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191029_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
