# Generated by Django 2.1.5 on 2019-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191029_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='large_price',
            field=models.FloatField(default=7.95),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small_price',
            field=models.FloatField(blank=True, default=6.5, null=True),
        ),
    ]
